env:
    browser: true
    es6: true
extends: 'eslint:recommended'
parserOptions:
    sourceType: module
    ecmaVersion: 2017
rules:
    indent:
        - error
        - tab
        - {
            SwitchCase: 1
        }
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-console:
        - off
